apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: python-flask-hello-world
    app.kubernetes.io/part-of: demo-app
  name: python-flask-hello-world
spec:
  replicas: 1
  selector:
    app.kubernetes.io/name: python-flask-hello-world
    app.kubernetes.io/part-of: demo-app
    matchLabels:
      app.kubernetes.io/name: python-flask-hello-world
  template:
    metadata:
      labels:
        app.kubernetes.io/name: python-flask-hello-world
        app.kubernetes.io/part-of: demo-app
      name: python-flask-hello-world
    spec:
      containers:
      - image: ghcr.io/amitisvoranu/demo-app/python-flask-hello-world:re-app-c3627a
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 5
          tcpSocket:
            port: 5000
        name: python-flask-hello-world
        ports:
        - containerPort: 5000
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 5
          tcpSocket:
            port: 5000
        resources:
          requests:
            memory: 128Mi
            cpu: 250m
          limits:
            memory: 256Mi
            cpu: 500m
      imagePullSecrets:
      - name: pull-secret
      restartPolicy: Always
