name: 'Re:App - CI/CD Pipeline for branch: $GITHUB_REF'

'on':
- push
- pull_request

jobs:
  build_push:
    name: Build and push the Docker images
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      actions: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build Docker image [${{ matrix.service.name }}]
      uses: docker/build-push-action@v6
      with:
        tags: ${{ github.action_repository }}/${{ matrix.service.name }}:${{ matrix.service.tags
          }}
        context: ./${{ matrix.service.contextPath }}
        dockerfile: ./${{ matrix.service.name }}/Dockerfile
        platforms: linux/amd64,linux/arm64
    - name: Push Docker image [${{ matrix.service.name }}]
      uses: docker/build-push-action@v6
      with:
        push: 'true'
        tags: ${{ github.action_repository }}/${{ matrix.service.name }}:${{ matrix.service.tags
          }}
        context: ./${{ matrix.service.contextPath }}
        dockerfile: ./${{ matrix.service.name }}/Dockerfile
        platforms: linux/amd64,linux/arm64
    strategy:
      matrix:
        service:
        - name: python-flask-hello-world
          contextPath: python-flask-hello-world
          tags: re-app-61bbcc
        - name: spring-boot-helloworld
          contextPath: spring-boot-hello-world
          tags: re-app-61bbcc
